name: Some fancy title 
url: http://ezsi.github.io
description: Java, Scala, Python, Machine Learning

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true
markdown: kramdown

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']